export default {
    SET_MOVIES: 'SET_MOVIES',
    SET_ERROR: 'SET_ERROR',
    MD_SET_MOVIES: 'MD_SET_MOVIES',
    SET_MOVIE_DETAILS: 'SET_MOVIE_DETAILS',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_TOTAL_PAGES: 'SET_TOTAL_PAGES'
};